const String INTERSTITIAL_VIDEO_ID = "ONESTORE_VIDEO";
const String INTERSTITIAL_ID = "ONESTORE_INTERSTITIAL";
const String REWARD_ID = "ONESTORE_REWARD_VIDEO";
const String NATIVE_ID = "ONESTORE_NATIVE";

const String BANNER_ID_320x50 = "ONESTORE_BANNER_320x50";
const String BANNER_ID_320x100 = "ONESTORE_BANNER_320x100";
const String BANNER_ID_300x250 = "ONESTORE_BANNER_300x250";


const String NATIVE_TEMPLATE_1 = "ONESTORE_NATIVE_TEMPLATE_1";
const String NATIVE_TEMPLATE_2 = "ONESTORE_NATIVE_TEMPLATE_2";
const String NATIVE_TEMPLATE_3 = "ONESTORE_NATIVE_TEMPLATE_3";
const String NATIVE_TEMPLATE_4 = "ONESTORE_NATIVE_TEMPLATE_4";
const String NATIVE_TEMPLATE_5 = "ONESTORE_NATIVE_TEMPLATE_5";
const String NATIVE_TEMPLATE_6 = "ONESTORE_NATIVE_TEMPLATE_6";
const String NATIVE_TEMPLATE_7 = "ONESTORE_NATIVE_TEMPLATE_7";
