class OamPlacementIds {
  static const String INTERSTITIAL_VIDEO_ID = "ONESTORE_VIDEO";
  static const String INTERSTITIAL_ID = "ONESTORE_INTERSTITIAL";
  static const String REWARD_ID = "ONESTORE_REWARD_VIDEO";
  static const String NATIVE_ID = "ONESTORE_NATIVE";

  static const String BANNER_ID_320x50 = "ONESTORE_BANNER_320x50";
  static const String BANNER_ID_320x100 = "ONESTORE_BANNER_320x100";
  static const String BANNER_ID_300x250 = "ONESTORE_BANNER_300x250";

  static const String NATIVE_TEMPLATE_1 = "ONESTORE_NATIVE_TEMPLATE_1";
  static const String NATIVE_TEMPLATE_2 = "ONESTORE_NATIVE_TEMPLATE_2";
  static const String NATIVE_TEMPLATE_3 = "ONESTORE_NATIVE_TEMPLATE_3";
  static const String NATIVE_TEMPLATE_4 = "ONESTORE_NATIVE_TEMPLATE_4";
  static const String NATIVE_TEMPLATE_5 = "ONESTORE_NATIVE_TEMPLATE_5";
  static const String NATIVE_TEMPLATE_6 = "ONESTORE_NATIVE_TEMPLATE_6";
  static const String NATIVE_TEMPLATE_7 = "ONESTORE_NATIVE_TEMPLATE_7";
}